name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * 1-4'  # Runs every day at 12:53 AM UTC (6:53 PM CST)
  workflow_dispatch:  # Enables manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Increment counter and commit
        run: |
          echo "Starting commit process..."
          python increment.py  # Run the Python script to increment the counter
          echo "Python script completed."
          
          git config --global user.name "JayyRaaj"  # Replace with your username
          git config --global user.email "iamgjraj@gmail.com"  # Replace with your email
          
          git add counter.txt
          git commit -m "Daily commit"
          
          # Log before pushing
          echo "Preparing to push changes to GitHub..."
          git push
          
          # Final log message
          echo "Changes pushed successfully."

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
